---
- hosts: 172.31.36.43
  become: yes
  gather_facts: yes
  tasks:
   - include_tasks: myfile.yml
   - name: install webservers
     apt:
      name: apache2
      state: present
     when: ansible_facts['os_family'] == "Debian"