---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: i want to install apache2 webserver
      apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: i want to start apache2 webserver
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"